# =============================================================
# Purview Asset Deleter — Configuration File
# Edit this file only — no need to touch purview_asset_deleter.py
# =============================================================

[FILES]
# Runtime output — generated every run
ASSETS_EXCEL  = purview_assets.xlsx

# Parameter file — download purview_assets.xlsx,
# fill delete column with yes/no, save as this file, run:
#   python purview_asset_deleter.py asset_params.xlsx
PARAMS_EXCEL  = asset_params.xlsx


[FILTERS]
# Control which assets are scanned
#
# FILTER_COLLECTIONS:
#   None                                           = scan everything
#   POC_Finastra/Lending-POS                       = one collection
#   POC_Finastra/UK Region, POC_Finastra/US Region = multiple
#
FILTER_COLLECTIONS = POC_Finastra/Azure SQL Task

# FILTER_DATA_SOURCES:
#   None                           = scan everything
#   finastra-onprem-oracle         = one source
#   finastra-onprem-oracle, other  = multiple sources
#
FILTER_DATA_SOURCES = Azure_storageaccount