# =============================================================
# Blob SQL to CSV — Configuration File
# Only blob folder/container settings here
# Credentials are hardcoded in blob_sql_to_blob_csv.py
# =============================================================
 
[BLOB]
CONTAINER_NAME      = poc
INPUT_BLOB_PREFIX   = Input
INPUT_ARCHIVE_BASE  = Input_archive
OUTPUT_BLOB_BASE    = Output
OUTPUT_ARCHIVE_BASE = Output_archive